version: '3'
services:
  nextcloud:
    image: "nextcloud:21.0.0-apache"
    container_name: nextcloud1
    restart: always
    ports:
      - 8080:80
    depends_on:
      - ldapservice
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=test
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=carlos
      - NEXTCLOUD_ADMIN_PASSWORD=test
  nextcloud2:
    image: "nextcloud:21.0.0-apache"
    container_name: nextcloud2
    restart: always
    ports:
      - 8081:81
    depends_on:
      - ldapservice
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=test
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=carlos
      - NEXTCLOUD_ADMIN_PASSWORD=test
  mariadb:
    image: "mariadb:10.4.8-bionic"
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  ldapservice:
    image: larrycai/openldap
    restart: always
    ports:
      - 389:389
      - 636:636
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 82:82
      - 443:443
    depends_on:
      - nextcloud
      - nextcloud2
volumes:
  nextcloud:
  db:
